apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-a5oo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-a5oo
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-a5oo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-a5oo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-a5oo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-byfn-tenant/nodejs-users/simple-nodejs-app-a5oo@sha256:bfedceaecc6fb13142cd4675ff14d54502e4cf9f8751e0b972182282ec534f88
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
